spring:
#  jpa:
#    database: mysql
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.211.132:3306/mysql?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
  data:
    mongodb:
      database: orderdish
      port: 27017
      host: 192.168.211.134

router:
  dish:
    url: http://localhost:8091
  order:
    url: http://localhost:8092
  payment:
    url: http://10.10.44.13:10005

api:
  key: secret

server:
  port: 8092
