#echo "123456" | base64
#MTIzNDU2Cg==
#echo "MTIzNDU2Cg==" | base64 -d
#123456

apiVersion: v1
kind: Secret
metadata:
  name: ea-secrets
type: Opaque
data:
  mysql: VGVzdDEyMzQ=
  jwtkey: VGVzdDEyMzQ=
  apikey: VGVzdDEyMzQ=
