apiVersion: apps/v1
kind: Deployment
metadata:
  name: ea-user-deployment
  labels:
    app: ea-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ea-user
  template:
    metadata:
      labels:
        app: ea-user
    spec:
      containers:
        - name: ea-user
          image: eaprojectsx/eapx-user
          ports:
            - containerPort: 8082
          env:
            - name: DB_HOST
              value: 'mongodb-service-mongodb-replicaset'
            - name: DB_PORT
              value: '27017'
            - name: DB_NAME
              value: 'user'
            - name: JWT_KEY
              valueFrom:
                  secretKeyRef:
                    name: ea-secrets
                    key: jwtkey
            - name: API_KEY
              valueFrom:
                  secretKeyRef:
                    name: ea-secrets
                    key: apikey
---
apiVersion: v1                  # API version
kind: Service                   # Type of kubernetes resource
metadata:
  name: ea-user-service      # Name of the kubernetes resource
spec:
  type: ClusterIP              # Exposes the service by opening a port on each node
  selector:
    app: ea-user
  ports:                        # Forward incoming connections on port 80 to the target port 80 in the Pod
    - name: http
      port: 8082 # Pod+Port
      targetPort: 8082 # Cluster IP or Service Name
