apiVersion: apps/v1
kind: Deployment
metadata:
  name: ea-auth-deployment
  labels:
    app: ea-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ea-auth
  template:
    metadata:
      labels:
        app: ea-auth
    spec:
      containers:
        - name: ea-auth
          image: eaprojectsx/ea-auth
          ports:
            - containerPort: 9999
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: ea-configs
                  key: ea-mysql-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: ea-configs
                  key: ea-mysql-port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: ea-configs
                  key: ea-mysql-db
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: ea-configs
                  key: ea-mysql-user
            - name: DB_PASSWD
              valueFrom:
                secretKeyRef:
                  name: ea-secrets
                  key: mysql
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: ea-secrets
                  key: jwtkey
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: ea-secrets
                  key: apikey
---
apiVersion: v1                  # API version
kind: Service                   # Type of kubernetes resource
metadata:
  name: ea-auth-service      # Name of the kubernetes resource
spec:
  type: ClusterIP              # Exposes the service by opening a port on each node
  selector:
    app: ea-auth
  ports:                        # Forward incoming connections on port 80 to the target port 80 in the Pod
    - name: http
      port: 9999 # Pod+Port
      targetPort: 9999 # Cluster IP or Service Name
